// @ts-check
/* ---------------------------------------------------------------------------
   PWAverse — app logic
   Plain JavaScript, no dependencies, no build step. Type-checked in-editor
   via `// @ts-check` + JSDoc (TypeScript's checker runs on this file as-is).
   Loads the community app list from data/apps.json and handles search,
   filtering, the detail dialog, and PWA installation.
--------------------------------------------------------------------------- */

/**
 * One entry in data/apps.json — field rules live in data/apps.schema.json.
 * @typedef {Object} App
 * @property {string} id
 * @property {string} name
 * @property {string} url
 * @property {string} description
 * @property {string} category
 * @property {string} iconLetter
 * @property {string} iconColor
 * @property {string[]} tags
 * @property {string} added
 * @property {string} submittedBy
 */

/**
 * Chrome's install event (not yet in the standard TS DOM lib).
 * @typedef {Event & {
 *   prompt: () => Promise<void>,
 *   userChoice: Promise<{ outcome: 'accepted' | 'dismissed' }>
 * }} BeforeInstallPromptEvent
 */

/**
 * One report card in data/scores.json (generated by scripts/score-pwas.mjs).
 * @typedef {Object} Score
 * @property {'good' | 'ok' | 'poor' | 'unknown'} installability
 * @property {'good' | 'ok' | 'poor' | 'unknown'} offline
 * @property {'good' | 'ok' | 'poor' | 'unknown'} ios
 * @property {'A' | 'B' | 'C' | '?'} grade
 * @property {string} checked
 */

const GITHUB_REPO_URL = 'https://github.com/Gacaca6/PWAverse';
const SUBMIT_APP_URL = `${GITHUB_REPO_URL}/issues/new?template=submit-app.yml`;

const state = {
  /** @type {App[]} */
  apps: [],
  /** @type {string[]} */
  categories: [],
  query: '',
  /** @type {string | null} */
  category: null,
  /** @type {Record<string, Score>} */
  scores: {},
  /** @type {Record<string, string>} */
  icons: {},
  /** @type {Record<string, string>} */
  screenshots: {},
};

const els = {
  grid: /** @type {HTMLElement} */ (document.getElementById('app-grid')),
  chips: /** @type {HTMLElement} */ (document.getElementById('category-chips')),
  search: /** @type {HTMLInputElement} */ (document.getElementById('search')),
  count: /** @type {HTMLElement} */ (document.getElementById('results-count')),
  empty: /** @type {HTMLElement} */ (document.getElementById('empty-state')),
  offlineBadge: /** @type {HTMLElement} */ (document.getElementById('offline-badge')),
  installBtn: /** @type {HTMLButtonElement} */ (document.getElementById('install-btn')),
  appDialog: /** @type {HTMLDialogElement} */ (document.getElementById('app-dialog')),
  dialogBody: /** @type {HTMLElement} */ (document.getElementById('dialog-body')),
  iosDialog: /** @type {HTMLDialogElement} */ (document.getElementById('ios-dialog')),
};

/* --- Data loading ---------------------------------------------------- */

async function loadApps() {
  // Report cards, real icons, and screenshots are optional enrichment —
  // the grid renders as each arrives, and never blocks on them.
  const enrichments = [
    fetch('data/scores.json')
      .then((res) => res.json())
      .then((/** @type {{ scores: Record<string, Score> }} */ data) => {
        state.scores = data.scores || {};
        render();
      })
      .catch(() => { /* no scores available — directory works without them */ }),

    fetch('data/icons.json')
      .then((res) => res.json())
      .then((/** @type {{ icons: Record<string, string> }} */ data) => {
        state.icons = data.icons || {};
        render();
      })
      .catch(() => { /* no icons available — letter tiles work fine */ }),

    fetch('data/screenshots.json')
      .then((res) => res.json())
      .then((/** @type {{ screenshots: Record<string, string> }} */ data) => {
        state.screenshots = data.screenshots || {};
      })
      .catch(() => { /* no screenshots — dialogs simply omit them */ }),
  ];

  try {
    const res = await fetch('data/apps.json');
    const data = /** @type {{ categories: string[], apps: App[] }} */ (await res.json());
    state.apps = data.apps;
    state.categories = data.categories;
    renderChips();
    render();
    // A deep-linked dialog should open fully dressed — wait for enrichments.
    await Promise.allSettled(enrichments);
    openFromHash();
  } catch (err) {
    els.grid.innerHTML = '';
    els.empty.hidden = false;
    els.empty.textContent = 'Could not load the app directory. Check your connection and refresh.';
    console.error('Failed to load apps.json', err);
  }
}

/* --- Rendering -------------------------------------------------------- */

/** @returns {App[]} */
function filteredApps() {
  const q = state.query.trim().toLowerCase();
  return state.apps.filter((app) => {
    if (state.category && app.category !== state.category) return false;
    if (!q) return true;
    const haystack = [app.name, app.description, app.category, ...(app.tags || [])]
      .join(' ')
      .toLowerCase();
    return q.split(/\s+/).every((term) => haystack.includes(term));
  });
}

function renderChips() {
  els.chips.innerHTML = '';
  const allChip = makeChip('All', null);
  allChip.setAttribute('aria-pressed', 'true');
  els.chips.appendChild(allChip);
  state.categories.forEach((cat) => els.chips.appendChild(makeChip(cat, cat)));
}

/**
 * @param {string} label
 * @param {string | null} value
 */
function makeChip(label, value) {
  const btn = document.createElement('button');
  btn.className = 'chip';
  btn.type = 'button';
  btn.textContent = label;
  btn.setAttribute('aria-pressed', 'false');
  btn.addEventListener('click', () => {
    state.category = value;
    els.chips.querySelectorAll('.chip').forEach((c) => c.setAttribute('aria-pressed', 'false'));
    btn.setAttribute('aria-pressed', 'true');
    render();
  });
  return btn;
}

/**
 * Small colored grade chip (A/B/C/?) shown on cards and in the dialog.
 * @param {Score} score
 */
function gradeBadge(score) {
  const badge = document.createElement('span');
  badge.className = `grade-badge grade-${score.grade === '?' ? 'unknown' : score.grade.toLowerCase()}`;
  badge.textContent = score.grade;
  badge.title = score.grade === '?'
    ? 'Unverified — this site blocks automated checks'
    : `PWA report card grade: ${score.grade}`;
  return badge;
}

/**
 * App tile: the app's real icon when we have one (fetched from its own
 * manifest by scripts/fetch-icons.mjs), otherwise the colored letter tile.
 * @param {App} app
 * @param {string} [extraClass]
 */
function appIcon(app, extraClass = '') {
  const icon = document.createElement('span');
  icon.className = `app-icon ${extraClass}`.trim();
  icon.setAttribute('aria-hidden', 'true');

  const showLetter = () => {
    icon.innerHTML = '';
    icon.style.background = app.iconColor || 'var(--accent)';
    icon.textContent = app.iconLetter || app.name[0];
  };

  const iconPath = state.icons[app.id];
  if (iconPath) {
    icon.style.background = 'var(--bg-soft)';
    const img = document.createElement('img');
    img.className = 'app-icon-img';
    img.src = iconPath;
    img.alt = '';
    img.loading = 'lazy';
    img.addEventListener('error', showLetter);
    icon.appendChild(img);
  } else {
    showLetter();
  }
  return icon;
}

function render() {
  const apps = filteredApps();
  els.grid.innerHTML = '';
  els.empty.hidden = apps.length > 0;
  els.count.textContent = `${apps.length} app${apps.length === 1 ? '' : 's'}`;

  apps.forEach((app) => {
    const card = document.createElement('button');
    card.className = 'app-card';
    card.type = 'button';

    const top = document.createElement('div');
    top.className = 'app-card-top';
    top.appendChild(appIcon(app));

    const titleWrap = document.createElement('div');
    const h3 = document.createElement('h3');
    h3.textContent = app.name;
    const cat = document.createElement('p');
    cat.className = 'app-category';
    cat.textContent = app.category;
    titleWrap.append(h3, cat);
    top.appendChild(titleWrap);

    const score = state.scores[app.id];
    if (score) top.appendChild(gradeBadge(score));

    const desc = document.createElement('p');
    desc.className = 'app-desc';
    desc.textContent = app.description;

    const tags = document.createElement('div');
    tags.className = 'app-tags';
    (app.tags || []).slice(0, 3).forEach((t) => {
      const tag = document.createElement('span');
      tag.className = 'tag';
      tag.textContent = t;
      tags.appendChild(tag);
    });

    card.append(top, desc, tags);
    card.addEventListener('click', () => openAppDialog(app));
    els.grid.appendChild(card);
  });
}

/* --- App detail dialog -------------------------------------------------- */

/**
 * Every app has a shareable deep link: <site>#app/<id>.
 * @param {App} app
 * @param {{ updateHash?: boolean }} [opts]
 */
function openAppDialog(app, { updateHash = true } = {}) {
  els.dialogBody.innerHTML = '';

  const header = document.createElement('div');
  header.className = 'dialog-app-header';
  header.appendChild(appIcon(app));

  const titleWrap = document.createElement('div');
  const h2 = document.createElement('h2');
  h2.id = 'dialog-title';
  h2.textContent = app.name;
  const meta = document.createElement('p');
  meta.textContent = `${app.category} · added ${app.added} · by ${app.submittedBy}`;
  titleWrap.append(h2, meta);
  header.appendChild(titleWrap);

  const desc = document.createElement('p');
  desc.textContent = app.description;

  const tags = document.createElement('div');
  tags.className = 'app-tags';
  (app.tags || []).forEach((t) => {
    const tag = document.createElement('span');
    tag.className = 'tag';
    tag.textContent = t;
    tags.appendChild(tag);
  });

  const launch = document.createElement('a');
  launch.className = 'btn btn-primary dialog-launch';
  launch.href = app.url;
  launch.target = '_blank';
  launch.rel = 'noopener';
  launch.textContent = `Launch ${app.name} →`;

  els.dialogBody.append(header);

  const shotPath = state.screenshots[app.id];
  if (shotPath) {
    const frame = document.createElement('div');
    frame.className = 'dialog-screenshot';
    const img = document.createElement('img');
    img.src = shotPath;
    img.alt = `Screenshot of ${app.name}`;
    // no loading="lazy" here: lazy images inside a modal <dialog> never load
    // in Chrome, and the screenshot is wanted immediately anyway
    img.addEventListener('error', () => frame.remove());
    frame.appendChild(img);
    els.dialogBody.append(frame);
  }

  els.dialogBody.append(desc, tags);
  const score = state.scores[app.id];
  if (score) els.dialogBody.append(reportCard(score));
  els.dialogBody.append(launch, shareRow(app));

  if (updateHash) history.replaceState(null, '', `#app/${app.id}`);
  els.appDialog.showModal();
}

/**
 * Copy-link / native-share row for an app's deep link.
 * @param {App} app
 */
function shareRow(app) {
  const link = `${location.origin}${location.pathname}#app/${app.id}`;
  const btn = document.createElement('button');
  btn.type = 'button';
  btn.className = 'btn btn-ghost dialog-share';
  btn.textContent = '🔗 Share this app';
  btn.addEventListener('click', async () => {
    try {
      if (navigator.share) {
        await navigator.share({ title: `${app.name} on PWAverse`, url: link });
      } else {
        await navigator.clipboard.writeText(link);
        btn.textContent = '✓ Link copied!';
        setTimeout(() => { btn.textContent = '🔗 Share this app'; }, 2000);
      }
    } catch { /* user cancelled the share sheet — nothing to do */ }
  });
  return btn;
}

function onAppDialogClosed() {
  if (location.hash.startsWith('#app/')) {
    history.replaceState(null, '', location.pathname + location.search);
  }
}
els.appDialog.addEventListener('close', onAppDialogClosed);
// Some Chromium builds deliver toggle but not close for <dialog> — cover both.
els.appDialog.addEventListener('toggle', (e) => {
  const toggle = /** @type {Event & { newState?: string }} */ (e);
  if (toggle.newState === 'closed') onAppDialogClosed();
});

/** Open the dialog for the app named in the URL hash, if any. */
function openFromHash() {
  const m = location.hash.match(/^#app\/(.+)$/);
  if (!m) return;
  const app = state.apps.find((a) => a.id === decodeURIComponent(m[1]));
  if (app) openAppDialog(app, { updateHash: false });
}

window.addEventListener('hashchange', () => {
  if (location.hash.startsWith('#app/')) openFromHash();
  else if (els.appDialog.open) els.appDialog.close();
});

/**
 * The per-app "PWA report card" panel shown in the detail dialog.
 * @param {Score} score
 */
function reportCard(score) {
  const DIM_LABELS = { good: 'Good', ok: 'OK', poor: 'Weak', unknown: 'Unverified' };
  const wrap = document.createElement('div');
  wrap.className = 'report-card';

  const head = document.createElement('div');
  head.className = 'report-head';
  const title = document.createElement('span');
  title.textContent = 'PWA report card';
  head.append(title, gradeBadge(score));
  wrap.appendChild(head);

  const rows = /** @type {const} */ ([
    ['Installability', score.installability],
    ['Offline ready', score.offline],
    ['iOS friendly', score.ios],
  ]);
  for (const [label, dim] of rows) {
    const row = document.createElement('div');
    row.className = 'report-row';
    const name = document.createElement('span');
    name.textContent = label;
    const value = document.createElement('span');
    value.className = `dim dim-${dim}`;
    value.textContent = DIM_LABELS[dim];
    row.append(name, value);
    wrap.appendChild(row);
  }

  const note = document.createElement('p');
  note.className = 'report-note';
  note.textContent = `Automated check · ${score.checked} · "Unverified" means the site hides this from robots — not that it's missing.`;
  wrap.appendChild(note);

  return wrap;
}

/* --- Search --------------------------------------------------------------- */

els.search.addEventListener('input', () => {
  state.query = els.search.value;
  render();
});

/* --- Install flow (beforeinstallprompt on Android/desktop, manual on iOS) -- */

/** @type {BeforeInstallPromptEvent | null} */
let deferredInstallPrompt = null;

const isIOS = /iphone|ipad|ipod/i.test(navigator.userAgent) ||
  (navigator.platform === 'MacIntel' && navigator.maxTouchPoints > 1);
const isStandalone = window.matchMedia('(display-mode: standalone)').matches ||
  /** @type {{ standalone?: boolean }} */ (window.navigator).standalone === true;

window.addEventListener('beforeinstallprompt', (e) => {
  e.preventDefault();
  deferredInstallPrompt = /** @type {BeforeInstallPromptEvent} */ (e);
  if (!isStandalone) els.installBtn.hidden = false;
});

if (isIOS && !isStandalone) {
  // iOS never fires beforeinstallprompt — offer manual instructions instead.
  els.installBtn.hidden = false;
}

els.installBtn.addEventListener('click', async () => {
  if (deferredInstallPrompt) {
    deferredInstallPrompt.prompt();
    const { outcome } = await deferredInstallPrompt.userChoice;
    if (outcome === 'accepted') els.installBtn.hidden = true;
    deferredInstallPrompt = null;
  } else if (isIOS) {
    els.iosDialog.showModal();
  }
});

window.addEventListener('appinstalled', () => {
  els.installBtn.hidden = true;
});

/* --- Online/offline indicator ---------------------------------------------- */

function updateOnlineStatus() {
  els.offlineBadge.hidden = navigator.onLine;
}
window.addEventListener('online', updateOnlineStatus);
window.addEventListener('offline', updateOnlineStatus);
updateOnlineStatus();

/* --- Repo links ------------------------------------------------------------- */

const githubLink = /** @type {HTMLAnchorElement} */ (document.getElementById('github-link'));
const submitLink = /** @type {HTMLAnchorElement} */ (document.getElementById('submit-link'));
githubLink.href = GITHUB_REPO_URL;
submitLink.href = SUBMIT_APP_URL;

/* --- Service worker ----------------------------------------------------------- */

if ('serviceWorker' in navigator) {
  window.addEventListener('load', () => {
    navigator.serviceWorker.register('sw.js').catch((err) => {
      console.error('Service worker registration failed:', err);
    });
  });
}

loadApps();
